PrestaShopCorp/prestashop_accounts_vue_components

package.json, src/components/PsAccounts.stories.mdx, src/components/PsAccounts.vue, src/components/panel/Account.stories.mdx, src/components/panel/Account.vue, src/lib/ContextValidator.js, src/locale/lang/en.json
Need to patch presenter in composer lib too!
=> ACCOUNT-327

src/components/PsAccounts.vue, src/components/panel/Account.vue
I dunno if it's the best way to do it since I didn't saw any css or scss assets file.
Anyway, we need to load BootstrapVue CSS (not only Bootstrap Vue) to make it work with Vue components.
I let you @xGouley if it's an OK solution or if it needs some refactor...
=> ACCOUNT-327 - Fixes the not showing tooltip

src/components/PsAccounts.stories.mdx, src/components/PsAccounts.vue, src/components/panel/Account.vue
Add events in actioned and viewed callbacks
How to use:
<PsAccount @actioned="action" @viewed="action" />
action(eventType, eventData) {
...
}
=> ACCOUNT-401 : event callbacks "actioned" and "viewed"

src/locale/lang/de.json, src/locale/lang/en.json, src/locale/lang/es.json, src/locale/lang/fr.json, src/locale/lang/it.json, src/locale/lang/nl.json, src/locale/lang/pl.json, src/locale/lang/pt.json, src/locale/lang/ru.json
New wording coming from https://docs.google.com/spreadsheets/d/1cUrvE3bOjbnrHlUmdXqUvK4MpezarDaF5Ke8oJT75Ms/edit#gid=0
=> WIP: feature/ new wording for all languages

.env, .env.example, .gitignore, src/components/PsAccounts.vue, src/components/alert/AccountUserEmailNotValidated.vue, src/components/alert/AccountUserNotSuperAdmin.vue, src/components/alert/PsAccountComponentAlertDisplay.vue, src/components/alert/subComponents/AccountNotEnabled.vue, src/components/alert/subComponents/AccountNotInstalled.vue, src/components/alert/subComponents/AccountNotUpdated.vue, src/components/alert/subComponents/EventBusNotInstalled.vue, src/components/crossdomains/LinkShopModal.vue, src/components/crossdomains/linkShopCrossDomain.js, src/components/panel/Account.vue, src/components/panel/accountSubComponents/AccountLinkToUi.vue, src/lib/ContextValidator.js
Isssue [#ACCOUNT-822](https://forge.prestashop.com/browse/ACCOUNT-822)
Voir les PRs sur [ps acounts](https://github.com/PrestaShopCorp/ps_accounts/pull/188) et  [accounts](https://github.com/PrestaShopCorp/accounts.prestashop.com/pull/52)
=> Add segment tracking

src/full.js
When we use the cdn, we don't automatically loads the languages, so we need to get it from storeAccounts
=> Cdn loads prestashop bo language

src/components/PsAccounts.vue
Issue:
- [ACCOUNT-862](https://forge.prestashop.com/browse/ACCOUNT-862)
I also removed the shop tree from the identify because when the public key changes the shop is duplicated in mix panel
=> Fix segment account component viewed event

src/components/panel/accountSubComponents/AccountLinkToUi.vue
=> Add selector id for associate button

src/components/PsAccounts.vue, src/components/alert/AccountUserEmailNotValidated.vue, src/components/alert/AccountUserNotSuperAdmin.vue, src/components/alert/subComponents/AccountNotEnabled.vue, src/components/alert/subComponents/AccountNotInstalled.vue, src/components/alert/subComponents/AccountNotUpdated.vue, src/components/alert/subComponents/EventBusNotInstalled.vue, src/components/crossdomains/LinkShopModal.vue, src/components/crossdomains/linkShopCrossDomain.js, src/components/panel/accountSubComponents/AccountLinkToUi.vue, src/full.js, src/plugins/tracking.js
Issue [#ACCOUNT-877](https://forge.prestashop.com/browse/ACCOUNT-877)
Sync w/ PrestaShopCorp/accounts.prestashop.com#109
Add a functionnality like mixpanel super properties.
This functionnality keep some property values between events
=> add 'super properties' like into segment/mixpanel

src/components/PsAccounts.vue, src/components/alert/subComponents/AccountNotInstalled.vue, src/full.js, src/plugins/tracking.js
Issue[ ACCOUNT-921](https://forge.prestashop.com/browse/ACCOUNT-921)
=> [ACCOUNT-921] PS Accounts not installed segment tracking

src/components/PsAccounts.vue, src/full.js, src/lib/ContextValidator.js
Depends of PrestaShopCorp/ps_accounts#228
=> Account 972: Add psaccounts version to context validator and component viewed tracking

src/full.js
PrestaShopCorp/accounts.prestashop.com#175
=> ACCOUNT-982: fix tracking multishop_numbers

src/components/PsAccounts.vue, src/components/alert/PsAccountComponentAlertDisplay.vue, src/components/alert/subComponents/EventBusNotEnabled.stories.mdx, src/components/alert/subComponents/EventBusNotEnabled.vue, src/lib/context.js, src/locale/lang/en.json
Fixes https://forge.prestashop.com/browse/EMKTG-1349
=> Handle case where PS EventBus is not enabled

.github/workflows/ci-cd-alpha.yml, .github/workflows/ci-cd-stable.yml, .github/workflows/ci.yml, .github/workflows/publish.yml
Fixes # (issue) / [ACCOUNT-XXXX](https://forge.prestashop.com/browse/ACCOUNT-XXXX)
Sync w/ PRs:
=> build: fix yarn build and upgrade github actions

README.md, src/components/crossdomains/linkShopCrossDomain.ts, src/shims-global.d.ts
Fixes # (issue) / [ACCOUNT-XXXX](https://forge.prestashop.com/browse/ACCOUNT-XXXX)
Sync w/ PRs:
=> [ACCOUNT-1600] fix: zoid error when tag already exist

src/lib/ContextValidator.ts, src/types/context.ts
Fixes # (issue) / [ACCOUNT-XXXX](https://forge.prestashop.com/browse/ACCOUNT-XXXX)
Sync w/ PRs:
- [X ] 🐞 Bug fix (a non-breaking change that fixes an issue)
=> [ACCOUNT-1591] fix: remove segmentApiKey from context

README.md
Remove production & integration links for storybook 
=> Docs - Remove storybook links from README

src/components/PsAccounts.vue, src/components/alert/AlertShopUnlinked.spec.ts, src/components/alert/AlertShopUnlinked.stories.ts, src/components/alert/AlertShopUnlinked.vue, src/lib/ContextValidator.ts, src/locales/en.json, src/locales/fr.json, src/types/components.d.ts, src/types/context.ts
Fixes # (issue) / [ACCOUNT-XXXX](https://forge.prestashop.com/browse/ACCOUNT-XXXX)
Sync w/ PRs:
=> [ACCOUNT-1553] feat: alert shop auto unlinked

src/locales/en.json
Fixes # (issue) / [ACCOUNT-2564](https://forge.prestashop.com/browse/ACCOUNT-2564)
Sync w/ PRs:
=> [ACCOUNT-2564] feat: unlinked alert

.github/workflows/ci.yml, .github/workflows/publish.yml, package.json, pnpm-lock.yaml, src/components/PsAccounts.stories.ts, src/components/PsAccounts.vue, src/components/alert/AlertModuleDependencies.spec.ts, src/components/alert/AlertModuleDependencies.stories.ts, src/components/alert/AlertModuleDependencies.vue, src/components/alert/AlertUpdateToLatest.spec.ts, src/components/alert/AlertUpdateToLatest.stories.ts, src/components/alert/AlertUpdateToLatest.vue, src/lib/ContextValidator.ts, src/locales/de.json, src/locales/en.json, src/locales/es.json, src/locales/fr.json, src/locales/it.json, src/locales/nl.json, src/locales/pl.json, src/locales/pt.json, src/locales/ro.json, src/locales/ru.json, src/types/components.d.ts, src/types/context.ts, tests/__mocks__/Context.ts
- Added an alert to upgrade Ps Accounts to latest when needed
Resolves [ACCOUNT-2380](https://forge.prestashop.com/browse/ACCOUNT-2380)
=> [Account-2380] Add alert banner for ps_account update

.github/workflows/ci.yml, .github/workflows/publish.yml, package.json, src/main.ts, src/types/window.d.ts
[ACCOUNT-2954](https://forge.prestashop.com/browse/ACCOUNT-2954)
[Accounts PR](https://github.com/PrestaShopCorp/accounts/pull/269)
=> [ACCOUNT-2954] Load v8 component if module accounts version is greater than or equal to 8
